Models/Tour.cs
using System.ComponentModel.DataAnnotations;

namespace GoTrip.Models
{
    public class Tour:BaseModel
    {
        [Required]
        public string Title { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public decimal Rating { get; set; }
        public string ImageURL { get; set; }
    }
}

Areas/AdminPanel/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoTrip.Areas.AdminPanel.Controllers
{
    [Authorize(Roles = "Admin, SuperAdmin")]
    [Area("AdminPanel")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Areas/AdminPanel/Controllers/TourController.cs
using GoTrip.Areas.AdminPanel.ViewModels;
using GoTrip.Data;
using GoTrip.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoTrip.Areas.AdminPanel.Controllers
{
    [Authorize(Roles ="Admin, SuperAdmin")]
    [Area("AdminPanel")]
    public class TourController : Controller
    {
        private TripDbContext _context { get; }
        public TourController(TripDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.tours.Where(c => !c.IsDeleted));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateVM vm)
        {
            if (!ModelState.IsValid) return View(vm);
            Tour tour = new Tour
            {
                Title=vm.title,
                Price=vm.price,
                Rating=vm.rating,
                IsDeleted=false
            };
            if (tour==null) return NotFound();
            if (vm.imageFile!=null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(vm.imageFile.FileName);
                string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "assets", "img", fileName);
                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {
                    await vm.imageFile.CopyToAsync(stream);
                }
                tour.ImageURL=fileName;
            }
            _context.Add(tour);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id==null) return BadRequest();
            Tour? tour = _context.tours.Where(c => !c.IsDeleted).FirstOrDefault(i=>i.Id==id);
            if (tour==null) return NotFound();
            tour.IsDeleted=true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int? id) 
        {
            if (id==null) return BadRequest();
            Tour? tour = _context.tours.Where(c => !c.IsDeleted).FirstOrDefault(i => i.Id==id);
            if (tour==null) return NotFound();
            UpdateVM vm = new UpdateVM
            {
                title=tour.Title,
                price=tour.Price,
                rating=tour.Rating,
                id_=tour.Id
            };
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UpdateVM vm) 
        {
            if (!ModelState.IsValid) return View(vm);
            Tour? tour = _context.tours.Where(c => !c.IsDeleted).FirstOrDefault(i => i.Id==vm.id_);
            if (tour==null) return NotFound();
            tour.Title=vm.title;
            tour.Price=vm.price;
            tour.Rating=vm.rating;
            if (vm.imageFile!=null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(vm.imageFile.FileName);
                string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "assets", "img", fileName);
                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {
                    await vm.imageFile.CopyToAsync(stream);
                }
                tour.ImageURL=fileName;
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Areas/AdminPanel/Views/Tour/Create.cshtml
@model CreateVM

<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create form</h4>

                <form class="forms-sample" method="post" enctype="multipart/form-data">

                    <div class="form-group">
                        <label asp-for="title">Enter your title</label>
                        <input type="text" class="form-control" asp-for="title" placeholder="Title">
                        <span class="text-danger" style="color:red;" asp-validation-for="title"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="price">Enter your price</label>
                        <input class="form-control" asp-for="price" placeholder="Price">
                        <span class="text-danger" style="color:red;" asp-validation-for="price"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="rating">Enter your rating</label>
                        <input asp-for="rating" class="form-control" placeholder="Rating">
                        <span class="text-danger" style="color:red;" asp-validation-for="rating"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="imageFile">Insert your image</label>
                        <input type="file" asp-for="imageFile" class="form-control" placeholder="Image">
                        <span class="text-danger" style="color:red;" asp-validation-for="imageFile"></span>
                    </div>


                    <button type="submit" class="btn btn-primary me-2" asp-action="Create" asp-controller="Tour">Submit</button>
                    <a class="btn btn-light" asp-action="Index" asp-controller="Dashboard">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

Areas/AdminPanel/Views/Tour/Index.cshtml
@model IEnumerable<Tour>
@{
	int count = 1;
}

<div class="row">
	<div class="col-lg-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				<h4 class="card-title">Tours table</h4>
				<a class="btn btn-primary" asp-action="Create" asp-controller="Tour">Create</a>
				<div class="table-responsive pt-3">
					<table class="table table-dark">
						<thead>
							<tr>
								<th>
									Count
								</th>
								<th>
									Title
								</th>
								<th>
									Price
								</th>
								<th>
									Rating
								</th>
								<th>
									Image
								</th>
								<th>
									Settings
								</th>
							</tr>
						</thead>

						<tbody>
							@foreach (var item in Model)
							{
								<tr>
									<td>
										@count
									</td>
									<td>
										@item.Title
									</td>
									<td>
										$ @item.Price
									</td>
									<td>
										@item.Rating
									</td>
										<td>
										<img src="~/assets/img/@item.ImageURL" alt="item">
									</td>
									<td>
										<a class="btn btn-warning" asp-action="Update" asp-controller="Tour" asp-route-id="@item.Id">Update</a>
										<a class="btn btn-danger" asp-action="Delete" asp-controller="Tour" asp-route-id="@item.Id">Delete</a>
									</td>
								</tr>
								count++;
							}
						

						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

Areas/AdminPanel/Views/Tour/Update.cshtml
@model UpdateVM

<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Update form</h4>

                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="id_" />

                    <div class="form-group">
                        <label asp-for="title">Enter your title</label>
                        <input type="text" class="form-control" asp-for="title" placeholder="Title">
                        <span class="text-danger" style="color:red;" asp-validation-for="title"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="price">Enter your price</label>
                        <input class="form-control" asp-for="price" placeholder="Price">
                        <span class="text-danger" style="color:red;" asp-validation-for="price"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="rating">Enter your rating</label>
                        <input asp-for="rating" class="form-control" placeholder="Rating">
                        <span class="text-danger" style="color:red;" asp-validation-for="rating"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="imageFile">Insert your image</label>
                        <input type="file" asp-for="imageFile" class="form-control" placeholder="Image">
                        <span class="text-danger" style="color:red;" asp-validation-for="imageFile"></span>
                    </div>


                    <button type="submit" class="btn btn-primary me-2">Submit</button>
                    <a class="btn btn-light" asp-action="Index" asp-controller="Dashboard">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>